### PR TITLE
clipfacevecs negative offset fix proposal

### PR DESCRIPTION
**Pull request by devnexen**
Changes proposed in this request:
- clipfacevecs: Fixing crash on party launch when negative offset access attempts

### CODE REVIEW

**Comment by Calinou** [comment]
Could you give some more context to reproduce the crash? Reading the PR description, I don't understand what's going on.

**Comment by devnexen** [comment]
After choosing a server and before the party begins I encounter a crash and looking at the root issue leads to negative access to the arrays aforementioned.

**Comment by qreeves** [comment]
This is not the correct solution to a problem of this kind. Please provide a backtrace of the crash so the originating function can be identified.

**Comment by qreeves** [comment]
More than one month without a response to a PR comment, closing.

**Pull request closed without merging**
