### PR TITLE
allow point lights to be linked to triggers

### PR DESCRIPTION
**Pull request by Jigoku**
Allows light entities to be directly linked to a trigger. 

There are a few use cases for this feature, one being that light sources for a sword weapon spawn (eg;volumetric light above the weapon platform) can be hidden when $mutsbitclassic isn't set. 

I'm not sure if i've missed anything, but seems to work fine from my testing locally.

### CODE REVIEW

**Comment by Jigoku** [comment]
Found a problem with this PR, existing maps end up with no lights emitting anything (even a /newent light). However, only a newmap being saved/loaded will work. Not sure why that happens though.

**Comment by q009** [comment]
I'd squash those commits into one

**Comment by qreeves** [comment]
I will get to this, but I have to be a bit more thorough with things that mess with entities and triggers.

**Comment by Jigoku** [comment]
fixed conflicts and using getlightfx() as suggesed for the spawned check

**Review by q009 — APPROVED** [review]
LGTM

**Comment by qreeves** [comment]
I'd rather leave these mediated through the `LIGHTFX` entity for now and put this on the backburner until a proper trigger system rewrite.

**Comment by Jigoku** [comment]
> I'd rather leave these mediated through the `LIGHTFX` entity for now and put this on the backburner until a proper trigger system rewrite.

it was fun playing with the concept, but i do agree with that.

**Pull request closed without merging**
