### PR TITLE
add password prompt for private servers

### PR DESCRIPTION
**Pull request by Jigoku**
Changes proposed in this request:
- add password prompt/input when clicking a server that is set to private

2020-07-23-195311_1920x1080_scrot

### CODE REVIEW

**Comment by qreeves** [comment]
Might be a good idea to show information about the server that's asking for a password, in case of accidental clicks, or any "WTF" moments. Maybe make it clear that it wants a password to connect because `serverpass` is set, but you can also use `adminpass` to get in.

**Comment by qreeves** [comment]
Bump.

**Comment by Jigoku** [comment]
Still unsure of the best approach to do this.

Is that fine to use a bunch of empty vars (to stop the console errors), passed to the other function as for:
```
ui_server_private_name = ""
ui_server_private_port = ""
ui_server_private_password = ""
```

Or whether there's a better way to do it.

**Comment by Jigoku** [comment]
Also, whether `adminpass` should be explicitly set/override, each time the server password is entered?

**Comment by qreeves** [comment]
Initialising those variables like that is normal. `adminpass` is only for the server, not the client.

**Comment by qreeves** [comment]
If that incorrect password still letting you into servers is still a thing, can you please make an issue for it?

**Pull request merged**
