### PR TITLE
Update guidelines.txt

### PR DESCRIPTION
**Pull request by swooboo**
Fix syntactic error - `be not be` --> `not be`

### CODE REVIEW

**Comment by swooboo** [comment]
Sorry, didn't think (and know how) to edit meaningful branch name, so it's `patch-1`...

**Comment by Calinou** [comment]
@swooboo The branch name is probably fine, you don't need to change it.

**Comment by swooboo** [comment]
Is there something else I should do to get this reviewed like assign a reviewer? Or is it just waiting till somebody reviews?

**Comment by qreeves** [comment]
Sorry, yes everything is fine, I'm just "on holiday". I probably should've labelled it so you knew what was going on.

**Comment by Calinou** [comment]
This can probably be merged now :slightly_smiling_face:

**Comment by qreeves** [comment]
Yeah I was getting the submodules out of the way first, then went and played with the kids for a while 😅

**Pull request merged**
