### PR TITLE
vangle/texangle commands for fine texture rotation

### PR DESCRIPTION
**Pull request by q009**
`vangle` and `texangle` allow rotation of textures in degrees.
A helper function exists that automatically calculates vangle based on the slope: `autotexangle`

### CODE REVIEW

**Comment by q009** [comment]
I still wonder whether it makes sense to bump the game version so soon, even if we added a new vslot property.

**Comment by qreeves** [comment]
Yeah, it'll have to wait for the next point release I think.

**Comment by q009** [comment]
I neglected to mention that there's an alternative way to implement this. A way that doesn't require any source code changes.

Instead of introducing a new vparam, one could simply define a new shader param and pass sin/cos values to it directly via setshaderparam. The only problem with this approach is the fact that shader parameters are not synchronized in coop, which is why I chose not to take this route.

**Comment by qreeves** [comment]
`vshaderparam`?

**Pull request merged**
